"""empty message

Revision ID: 002
Revises: 001
Create Date: 2025-03-18 00:30:44.252510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_download_items_queue_item_id'), 'download_items_queue', ['item_id'], unique=False)
    op.create_index(op.f('ix_download_items_queue_translator_id'), 'download_items_queue', ['translator_id'], unique=False)
    op.create_index(op.f('ix_downloaded_items_item_id'), 'downloaded_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_downloaded_items_translator_id'), 'downloaded_items', ['translator_id'], unique=False)
    op.create_index(op.f('ix_payments_tg_charge_id'), 'payments', ['tg_charge_id'], unique=False)
    op.create_index(op.f('ix_track_series_item_id'), 'track_series', ['item_id'], unique=False)
    op.create_index(op.f('ix_track_series_translator_id'), 'track_series', ['translator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_series_translator_id'), table_name='track_series')
    op.drop_index(op.f('ix_track_series_item_id'), table_name='track_series')
    op.drop_index(op.f('ix_payments_tg_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_downloaded_items_translator_id'), table_name='downloaded_items')
    op.drop_index(op.f('ix_downloaded_items_item_id'), table_name='downloaded_items')
    op.drop_index(op.f('ix_download_items_queue_translator_id'), table_name='download_items_queue')
    op.drop_index(op.f('ix_download_items_queue_item_id'), table_name='download_items_queue')
    # ### end Alembic commands ###
