"""Remove is_film from downloadeditem

Revision ID: 003
Revises: 002
Create Date: 2025-03-22 21:58:41.696071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloaded_items', 'is_film')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloaded_items', sa.Column('is_film', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
